// The complete, time-balanced reading curriculum: every verse of all 66 books, in canonical
// order, chunked so each day's passage takes roughly the same time to read/listen (~5-7
// minutes as a loose guideline, not a hard budget) instead of one fixed chapter regardless of
// length — Psalm 119 (176 verses) and Obadiah (21 verses) used to both count as "one day".
// Long chapters are split by verse range; short consecutive chapters are merged — but a chunk
// never crosses a book boundary in either direction, so a day's reading always stays inside
// one book (see scripts/rebuild-curriculum-by-time.ts for the migration that applied this).
//
// Regenerated 2026-07-20 from real per-chapter verse counts fetched from the NLT API
// (scripts/fetch-verse-counts.ts -> scripts/data/chapter-verse-counts.json) — the same source
// used for actual passage text, so pacing matches what's really read. Chunked by
// scripts/data/build-time-balanced-curriculum — target ~40 verses/entry.
// theme is plain English "Book Chapter[:verses]" scaffolding text fed to the model as light
// context for its prompt (see generateReading.ts) — never shown in the UI.
//
// Split out from seed.ts (which has a top-level side-effecting seed() call on import) so this
// data can also be imported by scripts/tune-curriculum-length.ts without triggering a seed run.
//
// Built from CHUNK_* sub-arrays (see bottom of file) rather than one flat literal — TypeScript
// chokes (TS2590) on a single huge literal checked against a union-typed field.
export type CurriculumEntry = {
  theme: string;
  book: string;
  passageRef: string;
  testament: "old" | "new";
};

const CHUNK_0: CurriculumEntry[] = [
  { theme: "Genesis 1", book: "Genesis", passageRef: "Genesis 1", testament: "old" },
  { theme: "Genesis 2-3", book: "Genesis", passageRef: "Genesis 2-3", testament: "old" },
  { theme: "Genesis 4", book: "Genesis", passageRef: "Genesis 4", testament: "old" },
  { theme: "Genesis 5", book: "Genesis", passageRef: "Genesis 5", testament: "old" },
  { theme: "Genesis 6-7", book: "Genesis", passageRef: "Genesis 6-7", testament: "old" },
  { theme: "Genesis 8-9", book: "Genesis", passageRef: "Genesis 8-9", testament: "old" },
  { theme: "Genesis 10", book: "Genesis", passageRef: "Genesis 10", testament: "old" },
  { theme: "Genesis 11-12", book: "Genesis", passageRef: "Genesis 11-12", testament: "old" },
  { theme: "Genesis 13-14", book: "Genesis", passageRef: "Genesis 13-14", testament: "old" },
  { theme: "Genesis 15-16", book: "Genesis", passageRef: "Genesis 15-16", testament: "old" },
  { theme: "Genesis 17", book: "Genesis", passageRef: "Genesis 17", testament: "old" },
  { theme: "Genesis 18", book: "Genesis", passageRef: "Genesis 18", testament: "old" },
  { theme: "Genesis 19", book: "Genesis", passageRef: "Genesis 19", testament: "old" },
  { theme: "Genesis 20-21", book: "Genesis", passageRef: "Genesis 20-21", testament: "old" },
  { theme: "Genesis 22-23", book: "Genesis", passageRef: "Genesis 22-23", testament: "old" },
  { theme: "Genesis 24:1-34", book: "Genesis", passageRef: "Genesis 24:1-34", testament: "old" },
  { theme: "Genesis 24:35-67", book: "Genesis", passageRef: "Genesis 24:35-67", testament: "old" },
  { theme: "Genesis 25", book: "Genesis", passageRef: "Genesis 25", testament: "old" },
  { theme: "Genesis 26", book: "Genesis", passageRef: "Genesis 26", testament: "old" },
  { theme: "Genesis 27", book: "Genesis", passageRef: "Genesis 27", testament: "old" },
  { theme: "Genesis 28", book: "Genesis", passageRef: "Genesis 28", testament: "old" },
  { theme: "Genesis 29", book: "Genesis", passageRef: "Genesis 29", testament: "old" },
  { theme: "Genesis 30", book: "Genesis", passageRef: "Genesis 30", testament: "old" },
  { theme: "Genesis 31", book: "Genesis", passageRef: "Genesis 31", testament: "old" },
  { theme: "Genesis 32-33", book: "Genesis", passageRef: "Genesis 32-33", testament: "old" },
  { theme: "Genesis 34", book: "Genesis", passageRef: "Genesis 34", testament: "old" },
  { theme: "Genesis 35", book: "Genesis", passageRef: "Genesis 35", testament: "old" },
  { theme: "Genesis 36", book: "Genesis", passageRef: "Genesis 36", testament: "old" },
  { theme: "Genesis 37", book: "Genesis", passageRef: "Genesis 37", testament: "old" },
  { theme: "Genesis 38", book: "Genesis", passageRef: "Genesis 38", testament: "old" },
  { theme: "Genesis 39-40", book: "Genesis", passageRef: "Genesis 39-40", testament: "old" },
  { theme: "Genesis 41", book: "Genesis", passageRef: "Genesis 41", testament: "old" },
  { theme: "Genesis 42", book: "Genesis", passageRef: "Genesis 42", testament: "old" },
  { theme: "Genesis 43", book: "Genesis", passageRef: "Genesis 43", testament: "old" },
  { theme: "Genesis 44", book: "Genesis", passageRef: "Genesis 44", testament: "old" },
  { theme: "Genesis 45", book: "Genesis", passageRef: "Genesis 45", testament: "old" },
  { theme: "Genesis 46", book: "Genesis", passageRef: "Genesis 46", testament: "old" },
  { theme: "Genesis 47", book: "Genesis", passageRef: "Genesis 47", testament: "old" },
  { theme: "Genesis 48", book: "Genesis", passageRef: "Genesis 48", testament: "old" },
  { theme: "Genesis 49", book: "Genesis", passageRef: "Genesis 49", testament: "old" },
  { theme: "Genesis 50", book: "Genesis", passageRef: "Genesis 50", testament: "old" },
  { theme: "Exodus 1-2", book: "Exodus", passageRef: "Exodus 1-2", testament: "old" },
  { theme: "Exodus 3", book: "Exodus", passageRef: "Exodus 3", testament: "old" },
  { theme: "Exodus 4", book: "Exodus", passageRef: "Exodus 4", testament: "old" },
  { theme: "Exodus 5", book: "Exodus", passageRef: "Exodus 5", testament: "old" },
  { theme: "Exodus 6", book: "Exodus", passageRef: "Exodus 6", testament: "old" },
  { theme: "Exodus 7", book: "Exodus", passageRef: "Exodus 7", testament: "old" },
  { theme: "Exodus 8", book: "Exodus", passageRef: "Exodus 8", testament: "old" },
  { theme: "Exodus 9", book: "Exodus", passageRef: "Exodus 9", testament: "old" },
  { theme: "Exodus 10-11", book: "Exodus", passageRef: "Exodus 10-11", testament: "old" },
  { theme: "Exodus 12", book: "Exodus", passageRef: "Exodus 12", testament: "old" },
  { theme: "Exodus 13", book: "Exodus", passageRef: "Exodus 13", testament: "old" },
  { theme: "Exodus 14", book: "Exodus", passageRef: "Exodus 14", testament: "old" },
  { theme: "Exodus 15", book: "Exodus", passageRef: "Exodus 15", testament: "old" },
  { theme: "Exodus 16-17", book: "Exodus", passageRef: "Exodus 16-17", testament: "old" },
  { theme: "Exodus 18-19", book: "Exodus", passageRef: "Exodus 18-19", testament: "old" },
  { theme: "Exodus 20", book: "Exodus", passageRef: "Exodus 20", testament: "old" },
  { theme: "Exodus 21", book: "Exodus", passageRef: "Exodus 21", testament: "old" },
  { theme: "Exodus 22", book: "Exodus", passageRef: "Exodus 22", testament: "old" },
  { theme: "Exodus 23-24", book: "Exodus", passageRef: "Exodus 23-24", testament: "old" },
  { theme: "Exodus 25", book: "Exodus", passageRef: "Exodus 25", testament: "old" },
  { theme: "Exodus 26", book: "Exodus", passageRef: "Exodus 26", testament: "old" },
  { theme: "Exodus 27", book: "Exodus", passageRef: "Exodus 27", testament: "old" },
  { theme: "Exodus 28", book: "Exodus", passageRef: "Exodus 28", testament: "old" },
  { theme: "Exodus 29", book: "Exodus", passageRef: "Exodus 29", testament: "old" },
  { theme: "Exodus 30", book: "Exodus", passageRef: "Exodus 30", testament: "old" },
  { theme: "Exodus 31", book: "Exodus", passageRef: "Exodus 31", testament: "old" },
  { theme: "Exodus 32", book: "Exodus", passageRef: "Exodus 32", testament: "old" },
  { theme: "Exodus 33", book: "Exodus", passageRef: "Exodus 33", testament: "old" },
  { theme: "Exodus 34", book: "Exodus", passageRef: "Exodus 34", testament: "old" },
  { theme: "Exodus 35", book: "Exodus", passageRef: "Exodus 35", testament: "old" },
  { theme: "Exodus 36", book: "Exodus", passageRef: "Exodus 36", testament: "old" },
  { theme: "Exodus 37", book: "Exodus", passageRef: "Exodus 37", testament: "old" },
  { theme: "Exodus 38", book: "Exodus", passageRef: "Exodus 38", testament: "old" },
  { theme: "Exodus 39", book: "Exodus", passageRef: "Exodus 39", testament: "old" },
  { theme: "Exodus 40", book: "Exodus", passageRef: "Exodus 40", testament: "old" },
  { theme: "Leviticus 1-3", book: "Leviticus", passageRef: "Leviticus 1-3", testament: "old" },
  { theme: "Leviticus 4", book: "Leviticus", passageRef: "Leviticus 4", testament: "old" },
  { theme: "Leviticus 5-6", book: "Leviticus", passageRef: "Leviticus 5-6", testament: "old" },
  { theme: "Leviticus 7", book: "Leviticus", passageRef: "Leviticus 7", testament: "old" },
  { theme: "Leviticus 8", book: "Leviticus", passageRef: "Leviticus 8", testament: "old" },
  { theme: "Leviticus 9-10", book: "Leviticus", passageRef: "Leviticus 9-10", testament: "old" },
  { theme: "Leviticus 11", book: "Leviticus", passageRef: "Leviticus 11", testament: "old" },
  { theme: "Leviticus 12", book: "Leviticus", passageRef: "Leviticus 12", testament: "old" },
  { theme: "Leviticus 13", book: "Leviticus", passageRef: "Leviticus 13", testament: "old" },
  { theme: "Leviticus 14", book: "Leviticus", passageRef: "Leviticus 14", testament: "old" },
  { theme: "Leviticus 15", book: "Leviticus", passageRef: "Leviticus 15", testament: "old" },
  { theme: "Leviticus 16-17", book: "Leviticus", passageRef: "Leviticus 16-17", testament: "old" },
  { theme: "Leviticus 18", book: "Leviticus", passageRef: "Leviticus 18", testament: "old" },
  { theme: "Leviticus 19", book: "Leviticus", passageRef: "Leviticus 19", testament: "old" },
  { theme: "Leviticus 20-21", book: "Leviticus", passageRef: "Leviticus 20-21", testament: "old" },
  { theme: "Leviticus 22", book: "Leviticus", passageRef: "Leviticus 22", testament: "old" },
  { theme: "Leviticus 23", book: "Leviticus", passageRef: "Leviticus 23", testament: "old" },
  { theme: "Leviticus 24", book: "Leviticus", passageRef: "Leviticus 24", testament: "old" },
  { theme: "Leviticus 25", book: "Leviticus", passageRef: "Leviticus 25", testament: "old" },
  { theme: "Leviticus 26", book: "Leviticus", passageRef: "Leviticus 26", testament: "old" },
  { theme: "Leviticus 27", book: "Leviticus", passageRef: "Leviticus 27", testament: "old" },
  { theme: "Numbers 1", book: "Numbers", passageRef: "Numbers 1", testament: "old" },
  { theme: "Numbers 2", book: "Numbers", passageRef: "Numbers 2", testament: "old" },
  { theme: "Numbers 3", book: "Numbers", passageRef: "Numbers 3", testament: "old" },
];

const CHUNK_1: CurriculumEntry[] = [
  { theme: "Numbers 4", book: "Numbers", passageRef: "Numbers 4", testament: "old" },
  { theme: "Numbers 5", book: "Numbers", passageRef: "Numbers 5", testament: "old" },
  { theme: "Numbers 6", book: "Numbers", passageRef: "Numbers 6", testament: "old" },
  { theme: "Numbers 7:1-30", book: "Numbers", passageRef: "Numbers 7:1-30", testament: "old" },
  { theme: "Numbers 7:31-60", book: "Numbers", passageRef: "Numbers 7:31-60", testament: "old" },
  { theme: "Numbers 7:61-89", book: "Numbers", passageRef: "Numbers 7:61-89", testament: "old" },
  { theme: "Numbers 8-9", book: "Numbers", passageRef: "Numbers 8-9", testament: "old" },
  { theme: "Numbers 10", book: "Numbers", passageRef: "Numbers 10", testament: "old" },
  { theme: "Numbers 11-12", book: "Numbers", passageRef: "Numbers 11-12", testament: "old" },
  { theme: "Numbers 13", book: "Numbers", passageRef: "Numbers 13", testament: "old" },
  { theme: "Numbers 14", book: "Numbers", passageRef: "Numbers 14", testament: "old" },
  { theme: "Numbers 15", book: "Numbers", passageRef: "Numbers 15", testament: "old" },
  { theme: "Numbers 16", book: "Numbers", passageRef: "Numbers 16", testament: "old" },
  { theme: "Numbers 17-18", book: "Numbers", passageRef: "Numbers 17-18", testament: "old" },
  { theme: "Numbers 19-20", book: "Numbers", passageRef: "Numbers 19-20", testament: "old" },
  { theme: "Numbers 21", book: "Numbers", passageRef: "Numbers 21", testament: "old" },
  { theme: "Numbers 22", book: "Numbers", passageRef: "Numbers 22", testament: "old" },
  { theme: "Numbers 23", book: "Numbers", passageRef: "Numbers 23", testament: "old" },
  { theme: "Numbers 24-25", book: "Numbers", passageRef: "Numbers 24-25", testament: "old" },
  { theme: "Numbers 26:1-33", book: "Numbers", passageRef: "Numbers 26:1-33", testament: "old" },
  { theme: "Numbers 26:34-65", book: "Numbers", passageRef: "Numbers 26:34-65", testament: "old" },
  { theme: "Numbers 27", book: "Numbers", passageRef: "Numbers 27", testament: "old" },
  { theme: "Numbers 28", book: "Numbers", passageRef: "Numbers 28", testament: "old" },
  { theme: "Numbers 29", book: "Numbers", passageRef: "Numbers 29", testament: "old" },
  { theme: "Numbers 30", book: "Numbers", passageRef: "Numbers 30", testament: "old" },
  { theme: "Numbers 31", book: "Numbers", passageRef: "Numbers 31", testament: "old" },
  { theme: "Numbers 32", book: "Numbers", passageRef: "Numbers 32", testament: "old" },
  { theme: "Numbers 33", book: "Numbers", passageRef: "Numbers 33", testament: "old" },
  { theme: "Numbers 34", book: "Numbers", passageRef: "Numbers 34", testament: "old" },
  { theme: "Numbers 35-36", book: "Numbers", passageRef: "Numbers 35-36", testament: "old" },
  { theme: "Deuteronomy 1", book: "Deuteronomy", passageRef: "Deuteronomy 1", testament: "old" },
  { theme: "Deuteronomy 2", book: "Deuteronomy", passageRef: "Deuteronomy 2", testament: "old" },
  { theme: "Deuteronomy 3", book: "Deuteronomy", passageRef: "Deuteronomy 3", testament: "old" },
  { theme: "Deuteronomy 4", book: "Deuteronomy", passageRef: "Deuteronomy 4", testament: "old" },
  { theme: "Deuteronomy 5", book: "Deuteronomy", passageRef: "Deuteronomy 5", testament: "old" },
  { theme: "Deuteronomy 6-7", book: "Deuteronomy", passageRef: "Deuteronomy 6-7", testament: "old" },
  { theme: "Deuteronomy 8-9", book: "Deuteronomy", passageRef: "Deuteronomy 8-9", testament: "old" },
  { theme: "Deuteronomy 10", book: "Deuteronomy", passageRef: "Deuteronomy 10", testament: "old" },
  { theme: "Deuteronomy 11", book: "Deuteronomy", passageRef: "Deuteronomy 11", testament: "old" },
  { theme: "Deuteronomy 12-13", book: "Deuteronomy", passageRef: "Deuteronomy 12-13", testament: "old" },
  { theme: "Deuteronomy 14-15", book: "Deuteronomy", passageRef: "Deuteronomy 14-15", testament: "old" },
  { theme: "Deuteronomy 16-17", book: "Deuteronomy", passageRef: "Deuteronomy 16-17", testament: "old" },
  { theme: "Deuteronomy 18-19", book: "Deuteronomy", passageRef: "Deuteronomy 18-19", testament: "old" },
  { theme: "Deuteronomy 20-21", book: "Deuteronomy", passageRef: "Deuteronomy 20-21", testament: "old" },
  { theme: "Deuteronomy 22", book: "Deuteronomy", passageRef: "Deuteronomy 22", testament: "old" },
  { theme: "Deuteronomy 23-24", book: "Deuteronomy", passageRef: "Deuteronomy 23-24", testament: "old" },
  { theme: "Deuteronomy 25-26", book: "Deuteronomy", passageRef: "Deuteronomy 25-26", testament: "old" },
  { theme: "Deuteronomy 27", book: "Deuteronomy", passageRef: "Deuteronomy 27", testament: "old" },
  { theme: "Deuteronomy 28:1-34", book: "Deuteronomy", passageRef: "Deuteronomy 28:1-34", testament: "old" },
  { theme: "Deuteronomy 28:35-68", book: "Deuteronomy", passageRef: "Deuteronomy 28:35-68", testament: "old" },
  { theme: "Deuteronomy 29-30", book: "Deuteronomy", passageRef: "Deuteronomy 29-30", testament: "old" },
  { theme: "Deuteronomy 31", book: "Deuteronomy", passageRef: "Deuteronomy 31", testament: "old" },
  { theme: "Deuteronomy 32", book: "Deuteronomy", passageRef: "Deuteronomy 32", testament: "old" },
  { theme: "Deuteronomy 33-34", book: "Deuteronomy", passageRef: "Deuteronomy 33-34", testament: "old" },
  { theme: "Joshua 1-2", book: "Joshua", passageRef: "Joshua 1-2", testament: "old" },
  { theme: "Joshua 3-4", book: "Joshua", passageRef: "Joshua 3-4", testament: "old" },
  { theme: "Joshua 5-6", book: "Joshua", passageRef: "Joshua 5-6", testament: "old" },
  { theme: "Joshua 7", book: "Joshua", passageRef: "Joshua 7", testament: "old" },
  { theme: "Joshua 8", book: "Joshua", passageRef: "Joshua 8", testament: "old" },
  { theme: "Joshua 9", book: "Joshua", passageRef: "Joshua 9", testament: "old" },
  { theme: "Joshua 10", book: "Joshua", passageRef: "Joshua 10", testament: "old" },
  { theme: "Joshua 11-12", book: "Joshua", passageRef: "Joshua 11-12", testament: "old" },
  { theme: "Joshua 13-14", book: "Joshua", passageRef: "Joshua 13-14", testament: "old" },
  { theme: "Joshua 15:1-32", book: "Joshua", passageRef: "Joshua 15:1-32", testament: "old" },
  { theme: "Joshua 15:33-63", book: "Joshua", passageRef: "Joshua 15:33-63", testament: "old" },
  { theme: "Joshua 16-17", book: "Joshua", passageRef: "Joshua 16-17", testament: "old" },
  { theme: "Joshua 18", book: "Joshua", passageRef: "Joshua 18", testament: "old" },
  { theme: "Joshua 19", book: "Joshua", passageRef: "Joshua 19", testament: "old" },
  { theme: "Joshua 20", book: "Joshua", passageRef: "Joshua 20", testament: "old" },
  { theme: "Joshua 21", book: "Joshua", passageRef: "Joshua 21", testament: "old" },
  { theme: "Joshua 22-23", book: "Joshua", passageRef: "Joshua 22-23", testament: "old" },
  { theme: "Joshua 24", book: "Joshua", passageRef: "Joshua 24", testament: "old" },
  { theme: "Judges 1", book: "Judges", passageRef: "Judges 1", testament: "old" },
  { theme: "Judges 2", book: "Judges", passageRef: "Judges 2", testament: "old" },
  { theme: "Judges 3", book: "Judges", passageRef: "Judges 3", testament: "old" },
  { theme: "Judges 4", book: "Judges", passageRef: "Judges 4", testament: "old" },
  { theme: "Judges 5", book: "Judges", passageRef: "Judges 5", testament: "old" },
  { theme: "Judges 6", book: "Judges", passageRef: "Judges 6", testament: "old" },
  { theme: "Judges 7", book: "Judges", passageRef: "Judges 7", testament: "old" },
  { theme: "Judges 8", book: "Judges", passageRef: "Judges 8", testament: "old" },
  { theme: "Judges 9", book: "Judges", passageRef: "Judges 9", testament: "old" },
  { theme: "Judges 10", book: "Judges", passageRef: "Judges 10", testament: "old" },
  { theme: "Judges 11", book: "Judges", passageRef: "Judges 11", testament: "old" },
  { theme: "Judges 12-13", book: "Judges", passageRef: "Judges 12-13", testament: "old" },
  { theme: "Judges 14-15", book: "Judges", passageRef: "Judges 14-15", testament: "old" },
  { theme: "Judges 16-17", book: "Judges", passageRef: "Judges 16-17", testament: "old" },
  { theme: "Judges 18", book: "Judges", passageRef: "Judges 18", testament: "old" },
  { theme: "Judges 19", book: "Judges", passageRef: "Judges 19", testament: "old" },
  { theme: "Judges 20", book: "Judges", passageRef: "Judges 20", testament: "old" },
  { theme: "Judges 21", book: "Judges", passageRef: "Judges 21", testament: "old" },
  { theme: "Ruth 1-2", book: "Ruth", passageRef: "Ruth 1-2", testament: "old" },
  { theme: "Ruth 3-4", book: "Ruth", passageRef: "Ruth 3-4", testament: "old" },
  { theme: "1 Samuel 1", book: "1 Samuel", passageRef: "1 Samuel 1", testament: "old" },
  { theme: "1 Samuel 2", book: "1 Samuel", passageRef: "1 Samuel 2", testament: "old" },
  { theme: "1 Samuel 3-4", book: "1 Samuel", passageRef: "1 Samuel 3-4", testament: "old" },
  { theme: "1 Samuel 5-7", book: "1 Samuel", passageRef: "1 Samuel 5-7", testament: "old" },
  { theme: "1 Samuel 8-9", book: "1 Samuel", passageRef: "1 Samuel 8-9", testament: "old" },
  { theme: "1 Samuel 10-11", book: "1 Samuel", passageRef: "1 Samuel 10-11", testament: "old" },
  { theme: "1 Samuel 12-13", book: "1 Samuel", passageRef: "1 Samuel 12-13", testament: "old" },
  { theme: "1 Samuel 14", book: "1 Samuel", passageRef: "1 Samuel 14", testament: "old" },
];

const CHUNK_2: CurriculumEntry[] = [
  { theme: "1 Samuel 15", book: "1 Samuel", passageRef: "1 Samuel 15", testament: "old" },
  { theme: "1 Samuel 16", book: "1 Samuel", passageRef: "1 Samuel 16", testament: "old" },
  { theme: "1 Samuel 17", book: "1 Samuel", passageRef: "1 Samuel 17", testament: "old" },
  { theme: "1 Samuel 18", book: "1 Samuel", passageRef: "1 Samuel 18", testament: "old" },
  { theme: "1 Samuel 19", book: "1 Samuel", passageRef: "1 Samuel 19", testament: "old" },
  { theme: "1 Samuel 20", book: "1 Samuel", passageRef: "1 Samuel 20", testament: "old" },
  { theme: "1 Samuel 21-22", book: "1 Samuel", passageRef: "1 Samuel 21-22", testament: "old" },
  { theme: "1 Samuel 23-24", book: "1 Samuel", passageRef: "1 Samuel 23-24", testament: "old" },
  { theme: "1 Samuel 25", book: "1 Samuel", passageRef: "1 Samuel 25", testament: "old" },
  { theme: "1 Samuel 26-27", book: "1 Samuel", passageRef: "1 Samuel 26-27", testament: "old" },
  { theme: "1 Samuel 28-29", book: "1 Samuel", passageRef: "1 Samuel 28-29", testament: "old" },
  { theme: "1 Samuel 30-31", book: "1 Samuel", passageRef: "1 Samuel 30-31", testament: "old" },
  { theme: "2 Samuel 1", book: "2 Samuel", passageRef: "2 Samuel 1", testament: "old" },
  { theme: "2 Samuel 2", book: "2 Samuel", passageRef: "2 Samuel 2", testament: "old" },
  { theme: "2 Samuel 3-4", book: "2 Samuel", passageRef: "2 Samuel 3-4", testament: "old" },
  { theme: "2 Samuel 5-6", book: "2 Samuel", passageRef: "2 Samuel 5-6", testament: "old" },
  { theme: "2 Samuel 7-8", book: "2 Samuel", passageRef: "2 Samuel 7-8", testament: "old" },
  { theme: "2 Samuel 9-10", book: "2 Samuel", passageRef: "2 Samuel 9-10", testament: "old" },
  { theme: "2 Samuel 11", book: "2 Samuel", passageRef: "2 Samuel 11", testament: "old" },
  { theme: "2 Samuel 12", book: "2 Samuel", passageRef: "2 Samuel 12", testament: "old" },
  { theme: "2 Samuel 13", book: "2 Samuel", passageRef: "2 Samuel 13", testament: "old" },
  { theme: "2 Samuel 14", book: "2 Samuel", passageRef: "2 Samuel 14", testament: "old" },
  { theme: "2 Samuel 15", book: "2 Samuel", passageRef: "2 Samuel 15", testament: "old" },
  { theme: "2 Samuel 16-17", book: "2 Samuel", passageRef: "2 Samuel 16-17", testament: "old" },
  { theme: "2 Samuel 18", book: "2 Samuel", passageRef: "2 Samuel 18", testament: "old" },
  { theme: "2 Samuel 19", book: "2 Samuel", passageRef: "2 Samuel 19", testament: "old" },
  { theme: "2 Samuel 20-21", book: "2 Samuel", passageRef: "2 Samuel 20-21", testament: "old" },
  { theme: "2 Samuel 22", book: "2 Samuel", passageRef: "2 Samuel 22", testament: "old" },
  { theme: "2 Samuel 23", book: "2 Samuel", passageRef: "2 Samuel 23", testament: "old" },
  { theme: "2 Samuel 24", book: "2 Samuel", passageRef: "2 Samuel 24", testament: "old" },
  { theme: "1 Kings 1", book: "1 Kings", passageRef: "1 Kings 1", testament: "old" },
  { theme: "1 Kings 2", book: "1 Kings", passageRef: "1 Kings 2", testament: "old" },
  { theme: "1 Kings 3", book: "1 Kings", passageRef: "1 Kings 3", testament: "old" },
  { theme: "1 Kings 4-5", book: "1 Kings", passageRef: "1 Kings 4-5", testament: "old" },
  { theme: "1 Kings 6", book: "1 Kings", passageRef: "1 Kings 6", testament: "old" },
  { theme: "1 Kings 7", book: "1 Kings", passageRef: "1 Kings 7", testament: "old" },
  { theme: "1 Kings 8:1-33", book: "1 Kings", passageRef: "1 Kings 8:1-33", testament: "old" },
  { theme: "1 Kings 8:34-66", book: "1 Kings", passageRef: "1 Kings 8:34-66", testament: "old" },
  { theme: "1 Kings 9", book: "1 Kings", passageRef: "1 Kings 9", testament: "old" },
  { theme: "1 Kings 10", book: "1 Kings", passageRef: "1 Kings 10", testament: "old" },
  { theme: "1 Kings 11", book: "1 Kings", passageRef: "1 Kings 11", testament: "old" },
  { theme: "1 Kings 12", book: "1 Kings", passageRef: "1 Kings 12", testament: "old" },
  { theme: "1 Kings 13", book: "1 Kings", passageRef: "1 Kings 13", testament: "old" },
  { theme: "1 Kings 14", book: "1 Kings", passageRef: "1 Kings 14", testament: "old" },
  { theme: "1 Kings 15", book: "1 Kings", passageRef: "1 Kings 15", testament: "old" },
  { theme: "1 Kings 16", book: "1 Kings", passageRef: "1 Kings 16", testament: "old" },
  { theme: "1 Kings 17", book: "1 Kings", passageRef: "1 Kings 17", testament: "old" },
  { theme: "1 Kings 18", book: "1 Kings", passageRef: "1 Kings 18", testament: "old" },
  { theme: "1 Kings 19", book: "1 Kings", passageRef: "1 Kings 19", testament: "old" },
  { theme: "1 Kings 20", book: "1 Kings", passageRef: "1 Kings 20", testament: "old" },
  { theme: "1 Kings 21", book: "1 Kings", passageRef: "1 Kings 21", testament: "old" },
  { theme: "1 Kings 22", book: "1 Kings", passageRef: "1 Kings 22", testament: "old" },
  { theme: "2 Kings 1-2", book: "2 Kings", passageRef: "2 Kings 1-2", testament: "old" },
  { theme: "2 Kings 3", book: "2 Kings", passageRef: "2 Kings 3", testament: "old" },
  { theme: "2 Kings 4", book: "2 Kings", passageRef: "2 Kings 4", testament: "old" },
  { theme: "2 Kings 5", book: "2 Kings", passageRef: "2 Kings 5", testament: "old" },
  { theme: "2 Kings 6", book: "2 Kings", passageRef: "2 Kings 6", testament: "old" },
  { theme: "2 Kings 7-8", book: "2 Kings", passageRef: "2 Kings 7-8", testament: "old" },
  { theme: "2 Kings 9", book: "2 Kings", passageRef: "2 Kings 9", testament: "old" },
  { theme: "2 Kings 10", book: "2 Kings", passageRef: "2 Kings 10", testament: "old" },
  { theme: "2 Kings 11-12", book: "2 Kings", passageRef: "2 Kings 11-12", testament: "old" },
  { theme: "2 Kings 13", book: "2 Kings", passageRef: "2 Kings 13", testament: "old" },
  { theme: "2 Kings 14", book: "2 Kings", passageRef: "2 Kings 14", testament: "old" },
  { theme: "2 Kings 15", book: "2 Kings", passageRef: "2 Kings 15", testament: "old" },
  { theme: "2 Kings 16", book: "2 Kings", passageRef: "2 Kings 16", testament: "old" },
  { theme: "2 Kings 17", book: "2 Kings", passageRef: "2 Kings 17", testament: "old" },
  { theme: "2 Kings 18", book: "2 Kings", passageRef: "2 Kings 18", testament: "old" },
  { theme: "2 Kings 19", book: "2 Kings", passageRef: "2 Kings 19", testament: "old" },
  { theme: "2 Kings 20-21", book: "2 Kings", passageRef: "2 Kings 20-21", testament: "old" },
  { theme: "2 Kings 22", book: "2 Kings", passageRef: "2 Kings 22", testament: "old" },
  { theme: "2 Kings 23", book: "2 Kings", passageRef: "2 Kings 23", testament: "old" },
  { theme: "2 Kings 24-25", book: "2 Kings", passageRef: "2 Kings 24-25", testament: "old" },
  { theme: "1 Chronicles 1", book: "1 Chronicles", passageRef: "1 Chronicles 1", testament: "old" },
  { theme: "1 Chronicles 2", book: "1 Chronicles", passageRef: "1 Chronicles 2", testament: "old" },
  { theme: "1 Chronicles 3", book: "1 Chronicles", passageRef: "1 Chronicles 3", testament: "old" },
  { theme: "1 Chronicles 4", book: "1 Chronicles", passageRef: "1 Chronicles 4", testament: "old" },
  { theme: "1 Chronicles 5", book: "1 Chronicles", passageRef: "1 Chronicles 5", testament: "old" },
  { theme: "1 Chronicles 6:1-27", book: "1 Chronicles", passageRef: "1 Chronicles 6:1-27", testament: "old" },
  { theme: "1 Chronicles 6:28-54", book: "1 Chronicles", passageRef: "1 Chronicles 6:28-54", testament: "old" },
  { theme: "1 Chronicles 6:55-81", book: "1 Chronicles", passageRef: "1 Chronicles 6:55-81", testament: "old" },
  { theme: "1 Chronicles 7", book: "1 Chronicles", passageRef: "1 Chronicles 7", testament: "old" },
  { theme: "1 Chronicles 8", book: "1 Chronicles", passageRef: "1 Chronicles 8", testament: "old" },
  { theme: "1 Chronicles 9", book: "1 Chronicles", passageRef: "1 Chronicles 9", testament: "old" },
  { theme: "1 Chronicles 10", book: "1 Chronicles", passageRef: "1 Chronicles 10", testament: "old" },
  { theme: "1 Chronicles 11", book: "1 Chronicles", passageRef: "1 Chronicles 11", testament: "old" },
  { theme: "1 Chronicles 12", book: "1 Chronicles", passageRef: "1 Chronicles 12", testament: "old" },
  { theme: "1 Chronicles 13-14", book: "1 Chronicles", passageRef: "1 Chronicles 13-14", testament: "old" },
  { theme: "1 Chronicles 15", book: "1 Chronicles", passageRef: "1 Chronicles 15", testament: "old" },
  { theme: "1 Chronicles 16", book: "1 Chronicles", passageRef: "1 Chronicles 16", testament: "old" },
  { theme: "1 Chronicles 17-18", book: "1 Chronicles", passageRef: "1 Chronicles 17-18", testament: "old" },
  { theme: "1 Chronicles 19-20", book: "1 Chronicles", passageRef: "1 Chronicles 19-20", testament: "old" },
  { theme: "1 Chronicles 21-22", book: "1 Chronicles", passageRef: "1 Chronicles 21-22", testament: "old" },
  { theme: "1 Chronicles 23", book: "1 Chronicles", passageRef: "1 Chronicles 23", testament: "old" },
  { theme: "1 Chronicles 24", book: "1 Chronicles", passageRef: "1 Chronicles 24", testament: "old" },
  { theme: "1 Chronicles 25", book: "1 Chronicles", passageRef: "1 Chronicles 25", testament: "old" },
  { theme: "1 Chronicles 26", book: "1 Chronicles", passageRef: "1 Chronicles 26", testament: "old" },
  { theme: "1 Chronicles 27", book: "1 Chronicles", passageRef: "1 Chronicles 27", testament: "old" },
  { theme: "1 Chronicles 28-29", book: "1 Chronicles", passageRef: "1 Chronicles 28-29", testament: "old" },
  { theme: "2 Chronicles 1-3", book: "2 Chronicles", passageRef: "2 Chronicles 1-3", testament: "old" },
  { theme: "2 Chronicles 4-5", book: "2 Chronicles", passageRef: "2 Chronicles 4-5", testament: "old" },
];

const CHUNK_3: CurriculumEntry[] = [
  { theme: "2 Chronicles 6", book: "2 Chronicles", passageRef: "2 Chronicles 6", testament: "old" },
  { theme: "2 Chronicles 7-8", book: "2 Chronicles", passageRef: "2 Chronicles 7-8", testament: "old" },
  { theme: "2 Chronicles 9-10", book: "2 Chronicles", passageRef: "2 Chronicles 9-10", testament: "old" },
  { theme: "2 Chronicles 11-12", book: "2 Chronicles", passageRef: "2 Chronicles 11-12", testament: "old" },
  { theme: "2 Chronicles 13-14", book: "2 Chronicles", passageRef: "2 Chronicles 13-14", testament: "old" },
  { theme: "2 Chronicles 15-17", book: "2 Chronicles", passageRef: "2 Chronicles 15-17", testament: "old" },
  { theme: "2 Chronicles 18-19", book: "2 Chronicles", passageRef: "2 Chronicles 18-19", testament: "old" },
  { theme: "2 Chronicles 20", book: "2 Chronicles", passageRef: "2 Chronicles 20", testament: "old" },
  { theme: "2 Chronicles 21-22", book: "2 Chronicles", passageRef: "2 Chronicles 21-22", testament: "old" },
  { theme: "2 Chronicles 23-24", book: "2 Chronicles", passageRef: "2 Chronicles 23-24", testament: "old" },
  { theme: "2 Chronicles 25-26", book: "2 Chronicles", passageRef: "2 Chronicles 25-26", testament: "old" },
  { theme: "2 Chronicles 27-28", book: "2 Chronicles", passageRef: "2 Chronicles 27-28", testament: "old" },
  { theme: "2 Chronicles 29", book: "2 Chronicles", passageRef: "2 Chronicles 29", testament: "old" },
  { theme: "2 Chronicles 30-31", book: "2 Chronicles", passageRef: "2 Chronicles 30-31", testament: "old" },
  { theme: "2 Chronicles 32", book: "2 Chronicles", passageRef: "2 Chronicles 32", testament: "old" },
  { theme: "2 Chronicles 33", book: "2 Chronicles", passageRef: "2 Chronicles 33", testament: "old" },
  { theme: "2 Chronicles 34", book: "2 Chronicles", passageRef: "2 Chronicles 34", testament: "old" },
  { theme: "2 Chronicles 35-36", book: "2 Chronicles", passageRef: "2 Chronicles 35-36", testament: "old" },
  { theme: "Ezra 1", book: "Ezra", passageRef: "Ezra 1", testament: "old" },
  { theme: "Ezra 2:1-35", book: "Ezra", passageRef: "Ezra 2:1-35", testament: "old" },
  { theme: "Ezra 2:36-70", book: "Ezra", passageRef: "Ezra 2:36-70", testament: "old" },
  { theme: "Ezra 3-4", book: "Ezra", passageRef: "Ezra 3-4", testament: "old" },
  { theme: "Ezra 5-6", book: "Ezra", passageRef: "Ezra 5-6", testament: "old" },
  { theme: "Ezra 7", book: "Ezra", passageRef: "Ezra 7", testament: "old" },
  { theme: "Ezra 8-9", book: "Ezra", passageRef: "Ezra 8-9", testament: "old" },
  { theme: "Ezra 10", book: "Ezra", passageRef: "Ezra 10", testament: "old" },
  { theme: "Nehemiah 1-2", book: "Nehemiah", passageRef: "Nehemiah 1-2", testament: "old" },
  { theme: "Nehemiah 3", book: "Nehemiah", passageRef: "Nehemiah 3", testament: "old" },
  { theme: "Nehemiah 4-5", book: "Nehemiah", passageRef: "Nehemiah 4-5", testament: "old" },
  { theme: "Nehemiah 6", book: "Nehemiah", passageRef: "Nehemiah 6", testament: "old" },
  { theme: "Nehemiah 7:1-37", book: "Nehemiah", passageRef: "Nehemiah 7:1-37", testament: "old" },
  { theme: "Nehemiah 7:38-73", book: "Nehemiah", passageRef: "Nehemiah 7:38-73", testament: "old" },
  { theme: "Nehemiah 8", book: "Nehemiah", passageRef: "Nehemiah 8", testament: "old" },
  { theme: "Nehemiah 9", book: "Nehemiah", passageRef: "Nehemiah 9", testament: "old" },
  { theme: "Nehemiah 10", book: "Nehemiah", passageRef: "Nehemiah 10", testament: "old" },
  { theme: "Nehemiah 11", book: "Nehemiah", passageRef: "Nehemiah 11", testament: "old" },
  { theme: "Nehemiah 12", book: "Nehemiah", passageRef: "Nehemiah 12", testament: "old" },
  { theme: "Nehemiah 13", book: "Nehemiah", passageRef: "Nehemiah 13", testament: "old" },
  { theme: "Esther 1-2", book: "Esther", passageRef: "Esther 1-2", testament: "old" },
  { theme: "Esther 3-5", book: "Esther", passageRef: "Esther 3-5", testament: "old" },
  { theme: "Esther 6-8", book: "Esther", passageRef: "Esther 6-8", testament: "old" },
  { theme: "Esther 9-10", book: "Esther", passageRef: "Esther 9-10", testament: "old" },
  { theme: "Job 1-2", book: "Job", passageRef: "Job 1-2", testament: "old" },
  { theme: "Job 3-4", book: "Job", passageRef: "Job 3-4", testament: "old" },
  { theme: "Job 5", book: "Job", passageRef: "Job 5", testament: "old" },
  { theme: "Job 6-7", book: "Job", passageRef: "Job 6-7", testament: "old" },
  { theme: "Job 8", book: "Job", passageRef: "Job 8", testament: "old" },
  { theme: "Job 9", book: "Job", passageRef: "Job 9", testament: "old" },
  { theme: "Job 10-11", book: "Job", passageRef: "Job 10-11", testament: "old" },
  { theme: "Job 12", book: "Job", passageRef: "Job 12", testament: "old" },
  { theme: "Job 13-14", book: "Job", passageRef: "Job 13-14", testament: "old" },
  { theme: "Job 15", book: "Job", passageRef: "Job 15", testament: "old" },
  { theme: "Job 16-17", book: "Job", passageRef: "Job 16-17", testament: "old" },
  { theme: "Job 18-19", book: "Job", passageRef: "Job 18-19", testament: "old" },
  { theme: "Job 20", book: "Job", passageRef: "Job 20", testament: "old" },
  { theme: "Job 21", book: "Job", passageRef: "Job 21", testament: "old" },
  { theme: "Job 22-23", book: "Job", passageRef: "Job 22-23", testament: "old" },
  { theme: "Job 24-26", book: "Job", passageRef: "Job 24-26", testament: "old" },
  { theme: "Job 27-28", book: "Job", passageRef: "Job 27-28", testament: "old" },
  { theme: "Job 29", book: "Job", passageRef: "Job 29", testament: "old" },
  { theme: "Job 30", book: "Job", passageRef: "Job 30", testament: "old" },
  { theme: "Job 31", book: "Job", passageRef: "Job 31", testament: "old" },
  { theme: "Job 32", book: "Job", passageRef: "Job 32", testament: "old" },
  { theme: "Job 33", book: "Job", passageRef: "Job 33", testament: "old" },
  { theme: "Job 34", book: "Job", passageRef: "Job 34", testament: "old" },
  { theme: "Job 35-36", book: "Job", passageRef: "Job 35-36", testament: "old" },
  { theme: "Job 37", book: "Job", passageRef: "Job 37", testament: "old" },
  { theme: "Job 38", book: "Job", passageRef: "Job 38", testament: "old" },
  { theme: "Job 39", book: "Job", passageRef: "Job 39", testament: "old" },
  { theme: "Job 40", book: "Job", passageRef: "Job 40", testament: "old" },
  { theme: "Job 41-42", book: "Job", passageRef: "Job 41-42", testament: "old" },
  { theme: "Psalm 1-5", book: "Psalms", passageRef: "Psalm 1-5", testament: "old" },
  { theme: "Psalm 6-8", book: "Psalms", passageRef: "Psalm 6-8", testament: "old" },
  { theme: "Psalm 9-11", book: "Psalms", passageRef: "Psalm 9-11", testament: "old" },
  { theme: "Psalm 12-17", book: "Psalms", passageRef: "Psalm 12-17", testament: "old" },
  { theme: "Psalm 18", book: "Psalms", passageRef: "Psalm 18", testament: "old" },
  { theme: "Psalm 19-21", book: "Psalms", passageRef: "Psalm 19-21", testament: "old" },
  { theme: "Psalm 22-24", book: "Psalms", passageRef: "Psalm 22-24", testament: "old" },
  { theme: "Psalm 25-27", book: "Psalms", passageRef: "Psalm 25-27", testament: "old" },
  { theme: "Psalm 28-30", book: "Psalms", passageRef: "Psalm 28-30", testament: "old" },
  { theme: "Psalm 31-32", book: "Psalms", passageRef: "Psalm 31-32", testament: "old" },
  { theme: "Psalm 33-34", book: "Psalms", passageRef: "Psalm 33-34", testament: "old" },
  { theme: "Psalm 35-36", book: "Psalms", passageRef: "Psalm 35-36", testament: "old" },
  { theme: "Psalm 37", book: "Psalms", passageRef: "Psalm 37", testament: "old" },
  { theme: "Psalm 38-40", book: "Psalms", passageRef: "Psalm 38-40", testament: "old" },
  { theme: "Psalm 41-43", book: "Psalms", passageRef: "Psalm 41-43", testament: "old" },
  { theme: "Psalm 44-45", book: "Psalms", passageRef: "Psalm 44-45", testament: "old" },
  { theme: "Psalm 46-48", book: "Psalms", passageRef: "Psalm 46-48", testament: "old" },
  { theme: "Psalm 49-50", book: "Psalms", passageRef: "Psalm 49-50", testament: "old" },
  { theme: "Psalm 51-54", book: "Psalms", passageRef: "Psalm 51-54", testament: "old" },
  { theme: "Psalm 55-57", book: "Psalms", passageRef: "Psalm 55-57", testament: "old" },
  { theme: "Psalm 58-61", book: "Psalms", passageRef: "Psalm 58-61", testament: "old" },
  { theme: "Psalm 62-65", book: "Psalms", passageRef: "Psalm 62-65", testament: "old" },
  { theme: "Psalm 66-67", book: "Psalms", passageRef: "Psalm 66-67", testament: "old" },
  { theme: "Psalm 68", book: "Psalms", passageRef: "Psalm 68", testament: "old" },
  { theme: "Psalm 69-70", book: "Psalms", passageRef: "Psalm 69-70", testament: "old" },
  { theme: "Psalm 71-72", book: "Psalms", passageRef: "Psalm 71-72", testament: "old" },
  { theme: "Psalm 73-74", book: "Psalms", passageRef: "Psalm 73-74", testament: "old" },
  { theme: "Psalm 75-77", book: "Psalms", passageRef: "Psalm 75-77", testament: "old" },
  { theme: "Psalm 78:1-36", book: "Psalms", passageRef: "Psalm 78:1-36", testament: "old" },
];

const CHUNK_4: CurriculumEntry[] = [
  { theme: "Psalm 78:37-72", book: "Psalms", passageRef: "Psalm 78:37-72", testament: "old" },
  { theme: "Psalm 79-81", book: "Psalms", passageRef: "Psalm 79-81", testament: "old" },
  { theme: "Psalm 82-85", book: "Psalms", passageRef: "Psalm 82-85", testament: "old" },
  { theme: "Psalm 86-88", book: "Psalms", passageRef: "Psalm 86-88", testament: "old" },
  { theme: "Psalm 89", book: "Psalms", passageRef: "Psalm 89", testament: "old" },
  { theme: "Psalm 90-92", book: "Psalms", passageRef: "Psalm 90-92", testament: "old" },
  { theme: "Psalm 93-96", book: "Psalms", passageRef: "Psalm 93-96", testament: "old" },
  { theme: "Psalm 97-101", book: "Psalms", passageRef: "Psalm 97-101", testament: "old" },
  { theme: "Psalm 102-103", book: "Psalms", passageRef: "Psalm 102-103", testament: "old" },
  { theme: "Psalm 104", book: "Psalms", passageRef: "Psalm 104", testament: "old" },
  { theme: "Psalm 105", book: "Psalms", passageRef: "Psalm 105", testament: "old" },
  { theme: "Psalm 106", book: "Psalms", passageRef: "Psalm 106", testament: "old" },
  { theme: "Psalm 107", book: "Psalms", passageRef: "Psalm 107", testament: "old" },
  { theme: "Psalm 108-110", book: "Psalms", passageRef: "Psalm 108-110", testament: "old" },
  { theme: "Psalm 111-114", book: "Psalms", passageRef: "Psalm 111-114", testament: "old" },
  { theme: "Psalm 115-117", book: "Psalms", passageRef: "Psalm 115-117", testament: "old" },
  { theme: "Psalm 118", book: "Psalms", passageRef: "Psalm 118", testament: "old" },
  { theme: "Psalm 119:1-36", book: "Psalms", passageRef: "Psalm 119:1-36", testament: "old" },
  { theme: "Psalm 119:37-72", book: "Psalms", passageRef: "Psalm 119:37-72", testament: "old" },
  { theme: "Psalm 119:73-108", book: "Psalms", passageRef: "Psalm 119:73-108", testament: "old" },
  { theme: "Psalm 119:109-144", book: "Psalms", passageRef: "Psalm 119:109-144", testament: "old" },
  { theme: "Psalm 119:145-176", book: "Psalms", passageRef: "Psalm 119:145-176", testament: "old" },
  { theme: "Psalm 120-127", book: "Psalms", passageRef: "Psalm 120-127", testament: "old" },
  { theme: "Psalm 128-134", book: "Psalms", passageRef: "Psalm 128-134", testament: "old" },
  { theme: "Psalm 135-136", book: "Psalms", passageRef: "Psalm 135-136", testament: "old" },
  { theme: "Psalm 137-139", book: "Psalms", passageRef: "Psalm 137-139", testament: "old" },
  { theme: "Psalm 140-143", book: "Psalms", passageRef: "Psalm 140-143", testament: "old" },
  { theme: "Psalm 144-146", book: "Psalms", passageRef: "Psalm 144-146", testament: "old" },
  { theme: "Psalm 147-150", book: "Psalms", passageRef: "Psalm 147-150", testament: "old" },
  { theme: "Proverbs 1", book: "Proverbs", passageRef: "Proverbs 1", testament: "old" },
  { theme: "Proverbs 2", book: "Proverbs", passageRef: "Proverbs 2", testament: "old" },
  { theme: "Proverbs 3", book: "Proverbs", passageRef: "Proverbs 3", testament: "old" },
  { theme: "Proverbs 4-5", book: "Proverbs", passageRef: "Proverbs 4-5", testament: "old" },
  { theme: "Proverbs 6", book: "Proverbs", passageRef: "Proverbs 6", testament: "old" },
  { theme: "Proverbs 7", book: "Proverbs", passageRef: "Proverbs 7", testament: "old" },
  { theme: "Proverbs 8", book: "Proverbs", passageRef: "Proverbs 8", testament: "old" },
  { theme: "Proverbs 9-10", book: "Proverbs", passageRef: "Proverbs 9-10", testament: "old" },
  { theme: "Proverbs 11", book: "Proverbs", passageRef: "Proverbs 11", testament: "old" },
  { theme: "Proverbs 12", book: "Proverbs", passageRef: "Proverbs 12", testament: "old" },
  { theme: "Proverbs 13", book: "Proverbs", passageRef: "Proverbs 13", testament: "old" },
  { theme: "Proverbs 14", book: "Proverbs", passageRef: "Proverbs 14", testament: "old" },
  { theme: "Proverbs 15", book: "Proverbs", passageRef: "Proverbs 15", testament: "old" },
  { theme: "Proverbs 16", book: "Proverbs", passageRef: "Proverbs 16", testament: "old" },
  { theme: "Proverbs 17-18", book: "Proverbs", passageRef: "Proverbs 17-18", testament: "old" },
  { theme: "Proverbs 19", book: "Proverbs", passageRef: "Proverbs 19", testament: "old" },
  { theme: "Proverbs 20", book: "Proverbs", passageRef: "Proverbs 20", testament: "old" },
  { theme: "Proverbs 21", book: "Proverbs", passageRef: "Proverbs 21", testament: "old" },
  { theme: "Proverbs 22", book: "Proverbs", passageRef: "Proverbs 22", testament: "old" },
  { theme: "Proverbs 23", book: "Proverbs", passageRef: "Proverbs 23", testament: "old" },
  { theme: "Proverbs 24", book: "Proverbs", passageRef: "Proverbs 24", testament: "old" },
  { theme: "Proverbs 25", book: "Proverbs", passageRef: "Proverbs 25", testament: "old" },
  { theme: "Proverbs 26", book: "Proverbs", passageRef: "Proverbs 26", testament: "old" },
  { theme: "Proverbs 27", book: "Proverbs", passageRef: "Proverbs 27", testament: "old" },
  { theme: "Proverbs 28", book: "Proverbs", passageRef: "Proverbs 28", testament: "old" },
  { theme: "Proverbs 29", book: "Proverbs", passageRef: "Proverbs 29", testament: "old" },
  { theme: "Proverbs 30", book: "Proverbs", passageRef: "Proverbs 30", testament: "old" },
  { theme: "Proverbs 31", book: "Proverbs", passageRef: "Proverbs 31", testament: "old" },
  { theme: "Ecclesiastes 1-2", book: "Ecclesiastes", passageRef: "Ecclesiastes 1-2", testament: "old" },
  { theme: "Ecclesiastes 3-4", book: "Ecclesiastes", passageRef: "Ecclesiastes 3-4", testament: "old" },
  { theme: "Ecclesiastes 5-6", book: "Ecclesiastes", passageRef: "Ecclesiastes 5-6", testament: "old" },
  { theme: "Ecclesiastes 7-8", book: "Ecclesiastes", passageRef: "Ecclesiastes 7-8", testament: "old" },
  { theme: "Ecclesiastes 9-11", book: "Ecclesiastes", passageRef: "Ecclesiastes 9-11", testament: "old" },
  { theme: "Ecclesiastes 12", book: "Ecclesiastes", passageRef: "Ecclesiastes 12", testament: "old" },
  { theme: "Song 1-3", book: "Song of Solomon", passageRef: "Song 1-3", testament: "old" },
  { theme: "Song 4-6", book: "Song of Solomon", passageRef: "Song 4-6", testament: "old" },
  { theme: "Song 7-8", book: "Song of Solomon", passageRef: "Song 7-8", testament: "old" },
  { theme: "Isaiah 1", book: "Isaiah", passageRef: "Isaiah 1", testament: "old" },
  { theme: "Isaiah 2-3", book: "Isaiah", passageRef: "Isaiah 2-3", testament: "old" },
  { theme: "Isaiah 4-6", book: "Isaiah", passageRef: "Isaiah 4-6", testament: "old" },
  { theme: "Isaiah 7-8", book: "Isaiah", passageRef: "Isaiah 7-8", testament: "old" },
  { theme: "Isaiah 9", book: "Isaiah", passageRef: "Isaiah 9", testament: "old" },
  { theme: "Isaiah 10-11", book: "Isaiah", passageRef: "Isaiah 10-11", testament: "old" },
  { theme: "Isaiah 12-13", book: "Isaiah", passageRef: "Isaiah 12-13", testament: "old" },
  { theme: "Isaiah 14-15", book: "Isaiah", passageRef: "Isaiah 14-15", testament: "old" },
  { theme: "Isaiah 16-18", book: "Isaiah", passageRef: "Isaiah 16-18", testament: "old" },
  { theme: "Isaiah 19-21", book: "Isaiah", passageRef: "Isaiah 19-21", testament: "old" },
  { theme: "Isaiah 22-23", book: "Isaiah", passageRef: "Isaiah 22-23", testament: "old" },
  { theme: "Isaiah 24-25", book: "Isaiah", passageRef: "Isaiah 24-25", testament: "old" },
  { theme: "Isaiah 26-27", book: "Isaiah", passageRef: "Isaiah 26-27", testament: "old" },
  { theme: "Isaiah 28", book: "Isaiah", passageRef: "Isaiah 28", testament: "old" },
  { theme: "Isaiah 29", book: "Isaiah", passageRef: "Isaiah 29", testament: "old" },
  { theme: "Isaiah 30-31", book: "Isaiah", passageRef: "Isaiah 30-31", testament: "old" },
  { theme: "Isaiah 32-33", book: "Isaiah", passageRef: "Isaiah 32-33", testament: "old" },
  { theme: "Isaiah 34-36", book: "Isaiah", passageRef: "Isaiah 34-36", testament: "old" },
  { theme: "Isaiah 37", book: "Isaiah", passageRef: "Isaiah 37", testament: "old" },
  { theme: "Isaiah 38-39", book: "Isaiah", passageRef: "Isaiah 38-39", testament: "old" },
  { theme: "Isaiah 40", book: "Isaiah", passageRef: "Isaiah 40", testament: "old" },
  { theme: "Isaiah 41", book: "Isaiah", passageRef: "Isaiah 41", testament: "old" },
  { theme: "Isaiah 42", book: "Isaiah", passageRef: "Isaiah 42", testament: "old" },
  { theme: "Isaiah 43", book: "Isaiah", passageRef: "Isaiah 43", testament: "old" },
  { theme: "Isaiah 44", book: "Isaiah", passageRef: "Isaiah 44", testament: "old" },
  { theme: "Isaiah 45-46", book: "Isaiah", passageRef: "Isaiah 45-46", testament: "old" },
  { theme: "Isaiah 47-48", book: "Isaiah", passageRef: "Isaiah 47-48", testament: "old" },
  { theme: "Isaiah 49-50", book: "Isaiah", passageRef: "Isaiah 49-50", testament: "old" },
  { theme: "Isaiah 51-53", book: "Isaiah", passageRef: "Isaiah 51-53", testament: "old" },
  { theme: "Isaiah 54-56", book: "Isaiah", passageRef: "Isaiah 54-56", testament: "old" },
  { theme: "Isaiah 57-58", book: "Isaiah", passageRef: "Isaiah 57-58", testament: "old" },
  { theme: "Isaiah 59-60", book: "Isaiah", passageRef: "Isaiah 59-60", testament: "old" },
  { theme: "Isaiah 61-63", book: "Isaiah", passageRef: "Isaiah 61-63", testament: "old" },
  { theme: "Isaiah 64-65", book: "Isaiah", passageRef: "Isaiah 64-65", testament: "old" },
];

const CHUNK_5: CurriculumEntry[] = [
  { theme: "Isaiah 66", book: "Isaiah", passageRef: "Isaiah 66", testament: "old" },
  { theme: "Jeremiah 1", book: "Jeremiah", passageRef: "Jeremiah 1", testament: "old" },
  { theme: "Jeremiah 2", book: "Jeremiah", passageRef: "Jeremiah 2", testament: "old" },
  { theme: "Jeremiah 3", book: "Jeremiah", passageRef: "Jeremiah 3", testament: "old" },
  { theme: "Jeremiah 4", book: "Jeremiah", passageRef: "Jeremiah 4", testament: "old" },
  { theme: "Jeremiah 5", book: "Jeremiah", passageRef: "Jeremiah 5", testament: "old" },
  { theme: "Jeremiah 6", book: "Jeremiah", passageRef: "Jeremiah 6", testament: "old" },
  { theme: "Jeremiah 7", book: "Jeremiah", passageRef: "Jeremiah 7", testament: "old" },
  { theme: "Jeremiah 8-9", book: "Jeremiah", passageRef: "Jeremiah 8-9", testament: "old" },
  { theme: "Jeremiah 10-11", book: "Jeremiah", passageRef: "Jeremiah 10-11", testament: "old" },
  { theme: "Jeremiah 12-13", book: "Jeremiah", passageRef: "Jeremiah 12-13", testament: "old" },
  { theme: "Jeremiah 14-15", book: "Jeremiah", passageRef: "Jeremiah 14-15", testament: "old" },
  { theme: "Jeremiah 16-17", book: "Jeremiah", passageRef: "Jeremiah 16-17", testament: "old" },
  { theme: "Jeremiah 18-19", book: "Jeremiah", passageRef: "Jeremiah 18-19", testament: "old" },
  { theme: "Jeremiah 20-21", book: "Jeremiah", passageRef: "Jeremiah 20-21", testament: "old" },
  { theme: "Jeremiah 22", book: "Jeremiah", passageRef: "Jeremiah 22", testament: "old" },
  { theme: "Jeremiah 23-24", book: "Jeremiah", passageRef: "Jeremiah 23-24", testament: "old" },
  { theme: "Jeremiah 25", book: "Jeremiah", passageRef: "Jeremiah 25", testament: "old" },
  { theme: "Jeremiah 26-27", book: "Jeremiah", passageRef: "Jeremiah 26-27", testament: "old" },
  { theme: "Jeremiah 28-29", book: "Jeremiah", passageRef: "Jeremiah 28-29", testament: "old" },
  { theme: "Jeremiah 30", book: "Jeremiah", passageRef: "Jeremiah 30", testament: "old" },
  { theme: "Jeremiah 31", book: "Jeremiah", passageRef: "Jeremiah 31", testament: "old" },
  { theme: "Jeremiah 32", book: "Jeremiah", passageRef: "Jeremiah 32", testament: "old" },
  { theme: "Jeremiah 33-34", book: "Jeremiah", passageRef: "Jeremiah 33-34", testament: "old" },
  { theme: "Jeremiah 35-36", book: "Jeremiah", passageRef: "Jeremiah 35-36", testament: "old" },
  { theme: "Jeremiah 37-38", book: "Jeremiah", passageRef: "Jeremiah 37-38", testament: "old" },
  { theme: "Jeremiah 39-41", book: "Jeremiah", passageRef: "Jeremiah 39-41", testament: "old" },
  { theme: "Jeremiah 42-43", book: "Jeremiah", passageRef: "Jeremiah 42-43", testament: "old" },
  { theme: "Jeremiah 44-45", book: "Jeremiah", passageRef: "Jeremiah 44-45", testament: "old" },
  { theme: "Jeremiah 46-47", book: "Jeremiah", passageRef: "Jeremiah 46-47", testament: "old" },
  { theme: "Jeremiah 48", book: "Jeremiah", passageRef: "Jeremiah 48", testament: "old" },
  { theme: "Jeremiah 49", book: "Jeremiah", passageRef: "Jeremiah 49", testament: "old" },
  { theme: "Jeremiah 50", book: "Jeremiah", passageRef: "Jeremiah 50", testament: "old" },
  { theme: "Jeremiah 51:1-32", book: "Jeremiah", passageRef: "Jeremiah 51:1-32", testament: "old" },
  { theme: "Jeremiah 51:33-64", book: "Jeremiah", passageRef: "Jeremiah 51:33-64", testament: "old" },
  { theme: "Jeremiah 52", book: "Jeremiah", passageRef: "Jeremiah 52", testament: "old" },
  { theme: "Lamentations 1-2", book: "Lamentations", passageRef: "Lamentations 1-2", testament: "old" },
  { theme: "Lamentations 3:1-33", book: "Lamentations", passageRef: "Lamentations 3:1-33", testament: "old" },
  { theme: "Lamentations 3:34-66", book: "Lamentations", passageRef: "Lamentations 3:34-66", testament: "old" },
  { theme: "Lamentations 4-5", book: "Lamentations", passageRef: "Lamentations 4-5", testament: "old" },
  { theme: "Ezekiel 1-2", book: "Ezekiel", passageRef: "Ezekiel 1-2", testament: "old" },
  { theme: "Ezekiel 3-4", book: "Ezekiel", passageRef: "Ezekiel 3-4", testament: "old" },
  { theme: "Ezekiel 5-6", book: "Ezekiel", passageRef: "Ezekiel 5-6", testament: "old" },
  { theme: "Ezekiel 7-8", book: "Ezekiel", passageRef: "Ezekiel 7-8", testament: "old" },
  { theme: "Ezekiel 9-10", book: "Ezekiel", passageRef: "Ezekiel 9-10", testament: "old" },
  { theme: "Ezekiel 11", book: "Ezekiel", passageRef: "Ezekiel 11", testament: "old" },
  { theme: "Ezekiel 12-13", book: "Ezekiel", passageRef: "Ezekiel 12-13", testament: "old" },
  { theme: "Ezekiel 14-15", book: "Ezekiel", passageRef: "Ezekiel 14-15", testament: "old" },
  { theme: "Ezekiel 16:1-32", book: "Ezekiel", passageRef: "Ezekiel 16:1-32", testament: "old" },
  { theme: "Ezekiel 16:33-63", book: "Ezekiel", passageRef: "Ezekiel 16:33-63", testament: "old" },
  { theme: "Ezekiel 17", book: "Ezekiel", passageRef: "Ezekiel 17", testament: "old" },
  { theme: "Ezekiel 18-19", book: "Ezekiel", passageRef: "Ezekiel 18-19", testament: "old" },
  { theme: "Ezekiel 20", book: "Ezekiel", passageRef: "Ezekiel 20", testament: "old" },
  { theme: "Ezekiel 21", book: "Ezekiel", passageRef: "Ezekiel 21", testament: "old" },
  { theme: "Ezekiel 22", book: "Ezekiel", passageRef: "Ezekiel 22", testament: "old" },
  { theme: "Ezekiel 23", book: "Ezekiel", passageRef: "Ezekiel 23", testament: "old" },
  { theme: "Ezekiel 24-25", book: "Ezekiel", passageRef: "Ezekiel 24-25", testament: "old" },
  { theme: "Ezekiel 26", book: "Ezekiel", passageRef: "Ezekiel 26", testament: "old" },
  { theme: "Ezekiel 27", book: "Ezekiel", passageRef: "Ezekiel 27", testament: "old" },
  { theme: "Ezekiel 28-29", book: "Ezekiel", passageRef: "Ezekiel 28-29", testament: "old" },
  { theme: "Ezekiel 30-31", book: "Ezekiel", passageRef: "Ezekiel 30-31", testament: "old" },
  { theme: "Ezekiel 32", book: "Ezekiel", passageRef: "Ezekiel 32", testament: "old" },
  { theme: "Ezekiel 33", book: "Ezekiel", passageRef: "Ezekiel 33", testament: "old" },
  { theme: "Ezekiel 34-35", book: "Ezekiel", passageRef: "Ezekiel 34-35", testament: "old" },
  { theme: "Ezekiel 36", book: "Ezekiel", passageRef: "Ezekiel 36", testament: "old" },
  { theme: "Ezekiel 37-38", book: "Ezekiel", passageRef: "Ezekiel 37-38", testament: "old" },
  { theme: "Ezekiel 39", book: "Ezekiel", passageRef: "Ezekiel 39", testament: "old" },
  { theme: "Ezekiel 40", book: "Ezekiel", passageRef: "Ezekiel 40", testament: "old" },
  { theme: "Ezekiel 41-42", book: "Ezekiel", passageRef: "Ezekiel 41-42", testament: "old" },
  { theme: "Ezekiel 43", book: "Ezekiel", passageRef: "Ezekiel 43", testament: "old" },
  { theme: "Ezekiel 44", book: "Ezekiel", passageRef: "Ezekiel 44", testament: "old" },
  { theme: "Ezekiel 45-46", book: "Ezekiel", passageRef: "Ezekiel 45-46", testament: "old" },
  { theme: "Ezekiel 47", book: "Ezekiel", passageRef: "Ezekiel 47", testament: "old" },
  { theme: "Ezekiel 48", book: "Ezekiel", passageRef: "Ezekiel 48", testament: "old" },
  { theme: "Daniel 1", book: "Daniel", passageRef: "Daniel 1", testament: "old" },
  { theme: "Daniel 2", book: "Daniel", passageRef: "Daniel 2", testament: "old" },
  { theme: "Daniel 3", book: "Daniel", passageRef: "Daniel 3", testament: "old" },
  { theme: "Daniel 4", book: "Daniel", passageRef: "Daniel 4", testament: "old" },
  { theme: "Daniel 5", book: "Daniel", passageRef: "Daniel 5", testament: "old" },
  { theme: "Daniel 6", book: "Daniel", passageRef: "Daniel 6", testament: "old" },
  { theme: "Daniel 7", book: "Daniel", passageRef: "Daniel 7", testament: "old" },
  { theme: "Daniel 8", book: "Daniel", passageRef: "Daniel 8", testament: "old" },
  { theme: "Daniel 9-10", book: "Daniel", passageRef: "Daniel 9-10", testament: "old" },
  { theme: "Daniel 11", book: "Daniel", passageRef: "Daniel 11", testament: "old" },
  { theme: "Daniel 12", book: "Daniel", passageRef: "Daniel 12", testament: "old" },
  { theme: "Hosea 1-3", book: "Hosea", passageRef: "Hosea 1-3", testament: "old" },
  { theme: "Hosea 4-6", book: "Hosea", passageRef: "Hosea 4-6", testament: "old" },
  { theme: "Hosea 7-9", book: "Hosea", passageRef: "Hosea 7-9", testament: "old" },
  { theme: "Hosea 10-12", book: "Hosea", passageRef: "Hosea 10-12", testament: "old" },
  { theme: "Hosea 13-14", book: "Hosea", passageRef: "Hosea 13-14", testament: "old" },
  { theme: "Joel 1-2", book: "Joel", passageRef: "Joel 1-2", testament: "old" },
  { theme: "Joel 3", book: "Joel", passageRef: "Joel 3", testament: "old" },
  { theme: "Amos 1-3", book: "Amos", passageRef: "Amos 1-3", testament: "old" },
  { theme: "Amos 4-5", book: "Amos", passageRef: "Amos 4-5", testament: "old" },
  { theme: "Amos 6-8", book: "Amos", passageRef: "Amos 6-8", testament: "old" },
  { theme: "Amos 9", book: "Amos", passageRef: "Amos 9", testament: "old" },
  { theme: "Obadiah 1", book: "Obadiah", passageRef: "Obadiah 1", testament: "old" },
  { theme: "Jonah 1-4", book: "Jonah", passageRef: "Jonah 1-4", testament: "old" },
  { theme: "Micah 1-3", book: "Micah", passageRef: "Micah 1-3", testament: "old" },
  { theme: "Micah 4-6", book: "Micah", passageRef: "Micah 4-6", testament: "old" },
];

const CHUNK_6: CurriculumEntry[] = [
  { theme: "Micah 7", book: "Micah", passageRef: "Micah 7", testament: "old" },
  { theme: "Nahum 1-3", book: "Nahum", passageRef: "Nahum 1-3", testament: "old" },
  { theme: "Habakkuk 1-2", book: "Habakkuk", passageRef: "Habakkuk 1-2", testament: "old" },
  { theme: "Habakkuk 3", book: "Habakkuk", passageRef: "Habakkuk 3", testament: "old" },
  { theme: "Zephaniah 1-2", book: "Zephaniah", passageRef: "Zephaniah 1-2", testament: "old" },
  { theme: "Zephaniah 3", book: "Zephaniah", passageRef: "Zephaniah 3", testament: "old" },
  { theme: "Haggai 1-2", book: "Haggai", passageRef: "Haggai 1-2", testament: "old" },
  { theme: "Zechariah 1-3", book: "Zechariah", passageRef: "Zechariah 1-3", testament: "old" },
  { theme: "Zechariah 4-6", book: "Zechariah", passageRef: "Zechariah 4-6", testament: "old" },
  { theme: "Zechariah 7-8", book: "Zechariah", passageRef: "Zechariah 7-8", testament: "old" },
  { theme: "Zechariah 9-11", book: "Zechariah", passageRef: "Zechariah 9-11", testament: "old" },
  { theme: "Zechariah 12-14", book: "Zechariah", passageRef: "Zechariah 12-14", testament: "old" },
  { theme: "Malachi 1-3", book: "Malachi", passageRef: "Malachi 1-3", testament: "old" },
  { theme: "Malachi 4", book: "Malachi", passageRef: "Malachi 4", testament: "old" },
  { theme: "Matthew 1-2", book: "Matthew", passageRef: "Matthew 1-2", testament: "new" },
  { theme: "Matthew 3-4", book: "Matthew", passageRef: "Matthew 3-4", testament: "new" },
  { theme: "Matthew 5", book: "Matthew", passageRef: "Matthew 5", testament: "new" },
  { theme: "Matthew 6", book: "Matthew", passageRef: "Matthew 6", testament: "new" },
  { theme: "Matthew 7", book: "Matthew", passageRef: "Matthew 7", testament: "new" },
  { theme: "Matthew 8", book: "Matthew", passageRef: "Matthew 8", testament: "new" },
  { theme: "Matthew 9", book: "Matthew", passageRef: "Matthew 9", testament: "new" },
  { theme: "Matthew 10", book: "Matthew", passageRef: "Matthew 10", testament: "new" },
  { theme: "Matthew 11", book: "Matthew", passageRef: "Matthew 11", testament: "new" },
  { theme: "Matthew 12", book: "Matthew", passageRef: "Matthew 12", testament: "new" },
  { theme: "Matthew 13", book: "Matthew", passageRef: "Matthew 13", testament: "new" },
  { theme: "Matthew 14", book: "Matthew", passageRef: "Matthew 14", testament: "new" },
  { theme: "Matthew 15", book: "Matthew", passageRef: "Matthew 15", testament: "new" },
  { theme: "Matthew 16", book: "Matthew", passageRef: "Matthew 16", testament: "new" },
  { theme: "Matthew 17", book: "Matthew", passageRef: "Matthew 17", testament: "new" },
  { theme: "Matthew 18", book: "Matthew", passageRef: "Matthew 18", testament: "new" },
  { theme: "Matthew 19", book: "Matthew", passageRef: "Matthew 19", testament: "new" },
  { theme: "Matthew 20", book: "Matthew", passageRef: "Matthew 20", testament: "new" },
  { theme: "Matthew 21", book: "Matthew", passageRef: "Matthew 21", testament: "new" },
  { theme: "Matthew 22", book: "Matthew", passageRef: "Matthew 22", testament: "new" },
  { theme: "Matthew 23", book: "Matthew", passageRef: "Matthew 23", testament: "new" },
  { theme: "Matthew 24", book: "Matthew", passageRef: "Matthew 24", testament: "new" },
  { theme: "Matthew 25", book: "Matthew", passageRef: "Matthew 25", testament: "new" },
  { theme: "Matthew 26:1-38", book: "Matthew", passageRef: "Matthew 26:1-38", testament: "new" },
  { theme: "Matthew 26:39-75", book: "Matthew", passageRef: "Matthew 26:39-75", testament: "new" },
  { theme: "Matthew 27:1-33", book: "Matthew", passageRef: "Matthew 27:1-33", testament: "new" },
  { theme: "Matthew 27:34-66", book: "Matthew", passageRef: "Matthew 27:34-66", testament: "new" },
  { theme: "Matthew 28", book: "Matthew", passageRef: "Matthew 28", testament: "new" },
  { theme: "Mark 1", book: "Mark", passageRef: "Mark 1", testament: "new" },
  { theme: "Mark 2", book: "Mark", passageRef: "Mark 2", testament: "new" },
  { theme: "Mark 3", book: "Mark", passageRef: "Mark 3", testament: "new" },
  { theme: "Mark 4", book: "Mark", passageRef: "Mark 4", testament: "new" },
  { theme: "Mark 5", book: "Mark", passageRef: "Mark 5", testament: "new" },
  { theme: "Mark 6", book: "Mark", passageRef: "Mark 6", testament: "new" },
  { theme: "Mark 7", book: "Mark", passageRef: "Mark 7", testament: "new" },
  { theme: "Mark 8", book: "Mark", passageRef: "Mark 8", testament: "new" },
  { theme: "Mark 9", book: "Mark", passageRef: "Mark 9", testament: "new" },
  { theme: "Mark 10", book: "Mark", passageRef: "Mark 10", testament: "new" },
  { theme: "Mark 11", book: "Mark", passageRef: "Mark 11", testament: "new" },
  { theme: "Mark 12", book: "Mark", passageRef: "Mark 12", testament: "new" },
  { theme: "Mark 13", book: "Mark", passageRef: "Mark 13", testament: "new" },
  { theme: "Mark 14:1-36", book: "Mark", passageRef: "Mark 14:1-36", testament: "new" },
  { theme: "Mark 14:37-72", book: "Mark", passageRef: "Mark 14:37-72", testament: "new" },
  { theme: "Mark 15", book: "Mark", passageRef: "Mark 15", testament: "new" },
  { theme: "Mark 16", book: "Mark", passageRef: "Mark 16", testament: "new" },
  { theme: "Luke 1:1-40", book: "Luke", passageRef: "Luke 1:1-40", testament: "new" },
  { theme: "Luke 1:41-80", book: "Luke", passageRef: "Luke 1:41-80", testament: "new" },
  { theme: "Luke 2", book: "Luke", passageRef: "Luke 2", testament: "new" },
  { theme: "Luke 3", book: "Luke", passageRef: "Luke 3", testament: "new" },
  { theme: "Luke 4", book: "Luke", passageRef: "Luke 4", testament: "new" },
  { theme: "Luke 5", book: "Luke", passageRef: "Luke 5", testament: "new" },
  { theme: "Luke 6", book: "Luke", passageRef: "Luke 6", testament: "new" },
  { theme: "Luke 7", book: "Luke", passageRef: "Luke 7", testament: "new" },
  { theme: "Luke 8", book: "Luke", passageRef: "Luke 8", testament: "new" },
  { theme: "Luke 9:1-31", book: "Luke", passageRef: "Luke 9:1-31", testament: "new" },
  { theme: "Luke 9:32-62", book: "Luke", passageRef: "Luke 9:32-62", testament: "new" },
  { theme: "Luke 10", book: "Luke", passageRef: "Luke 10", testament: "new" },
  { theme: "Luke 11", book: "Luke", passageRef: "Luke 11", testament: "new" },
  { theme: "Luke 12", book: "Luke", passageRef: "Luke 12", testament: "new" },
  { theme: "Luke 13", book: "Luke", passageRef: "Luke 13", testament: "new" },
  { theme: "Luke 14", book: "Luke", passageRef: "Luke 14", testament: "new" },
  { theme: "Luke 15", book: "Luke", passageRef: "Luke 15", testament: "new" },
  { theme: "Luke 16", book: "Luke", passageRef: "Luke 16", testament: "new" },
  { theme: "Luke 17", book: "Luke", passageRef: "Luke 17", testament: "new" },
  { theme: "Luke 18", book: "Luke", passageRef: "Luke 18", testament: "new" },
  { theme: "Luke 19", book: "Luke", passageRef: "Luke 19", testament: "new" },
  { theme: "Luke 20", book: "Luke", passageRef: "Luke 20", testament: "new" },
  { theme: "Luke 21", book: "Luke", passageRef: "Luke 21", testament: "new" },
  { theme: "Luke 22:1-36", book: "Luke", passageRef: "Luke 22:1-36", testament: "new" },
  { theme: "Luke 22:37-71", book: "Luke", passageRef: "Luke 22:37-71", testament: "new" },
  { theme: "Luke 23", book: "Luke", passageRef: "Luke 23", testament: "new" },
  { theme: "Luke 24", book: "Luke", passageRef: "Luke 24", testament: "new" },
  { theme: "John 1", book: "John", passageRef: "John 1", testament: "new" },
  { theme: "John 2", book: "John", passageRef: "John 2", testament: "new" },
  { theme: "John 3", book: "John", passageRef: "John 3", testament: "new" },
  { theme: "John 4", book: "John", passageRef: "John 4", testament: "new" },
  { theme: "John 5", book: "John", passageRef: "John 5", testament: "new" },
  { theme: "John 6:1-36", book: "John", passageRef: "John 6:1-36", testament: "new" },
  { theme: "John 6:37-71", book: "John", passageRef: "John 6:37-71", testament: "new" },
  { theme: "John 7", book: "John", passageRef: "John 7", testament: "new" },
  { theme: "John 8", book: "John", passageRef: "John 8", testament: "new" },
  { theme: "John 9", book: "John", passageRef: "John 9", testament: "new" },
  { theme: "John 10", book: "John", passageRef: "John 10", testament: "new" },
  { theme: "John 11", book: "John", passageRef: "John 11", testament: "new" },
  { theme: "John 12", book: "John", passageRef: "John 12", testament: "new" },
  { theme: "John 13", book: "John", passageRef: "John 13", testament: "new" },
];

const CHUNK_7: CurriculumEntry[] = [
  { theme: "John 14", book: "John", passageRef: "John 14", testament: "new" },
  { theme: "John 15", book: "John", passageRef: "John 15", testament: "new" },
  { theme: "John 16", book: "John", passageRef: "John 16", testament: "new" },
  { theme: "John 17", book: "John", passageRef: "John 17", testament: "new" },
  { theme: "John 18", book: "John", passageRef: "John 18", testament: "new" },
  { theme: "John 19", book: "John", passageRef: "John 19", testament: "new" },
  { theme: "John 20", book: "John", passageRef: "John 20", testament: "new" },
  { theme: "John 21", book: "John", passageRef: "John 21", testament: "new" },
  { theme: "Acts 1", book: "Acts", passageRef: "Acts 1", testament: "new" },
  { theme: "Acts 2", book: "Acts", passageRef: "Acts 2", testament: "new" },
  { theme: "Acts 3", book: "Acts", passageRef: "Acts 3", testament: "new" },
  { theme: "Acts 4", book: "Acts", passageRef: "Acts 4", testament: "new" },
  { theme: "Acts 5", book: "Acts", passageRef: "Acts 5", testament: "new" },
  { theme: "Acts 6", book: "Acts", passageRef: "Acts 6", testament: "new" },
  { theme: "Acts 7", book: "Acts", passageRef: "Acts 7", testament: "new" },
  { theme: "Acts 8", book: "Acts", passageRef: "Acts 8", testament: "new" },
  { theme: "Acts 9", book: "Acts", passageRef: "Acts 9", testament: "new" },
  { theme: "Acts 10", book: "Acts", passageRef: "Acts 10", testament: "new" },
  { theme: "Acts 11", book: "Acts", passageRef: "Acts 11", testament: "new" },
  { theme: "Acts 12", book: "Acts", passageRef: "Acts 12", testament: "new" },
  { theme: "Acts 13", book: "Acts", passageRef: "Acts 13", testament: "new" },
  { theme: "Acts 14", book: "Acts", passageRef: "Acts 14", testament: "new" },
  { theme: "Acts 15", book: "Acts", passageRef: "Acts 15", testament: "new" },
  { theme: "Acts 16", book: "Acts", passageRef: "Acts 16", testament: "new" },
  { theme: "Acts 17", book: "Acts", passageRef: "Acts 17", testament: "new" },
  { theme: "Acts 18", book: "Acts", passageRef: "Acts 18", testament: "new" },
  { theme: "Acts 19", book: "Acts", passageRef: "Acts 19", testament: "new" },
  { theme: "Acts 20", book: "Acts", passageRef: "Acts 20", testament: "new" },
  { theme: "Acts 21", book: "Acts", passageRef: "Acts 21", testament: "new" },
  { theme: "Acts 22", book: "Acts", passageRef: "Acts 22", testament: "new" },
  { theme: "Acts 23", book: "Acts", passageRef: "Acts 23", testament: "new" },
  { theme: "Acts 24", book: "Acts", passageRef: "Acts 24", testament: "new" },
  { theme: "Acts 25", book: "Acts", passageRef: "Acts 25", testament: "new" },
  { theme: "Acts 26", book: "Acts", passageRef: "Acts 26", testament: "new" },
  { theme: "Acts 27", book: "Acts", passageRef: "Acts 27", testament: "new" },
  { theme: "Acts 28", book: "Acts", passageRef: "Acts 28", testament: "new" },
  { theme: "Romans 1", book: "Romans", passageRef: "Romans 1", testament: "new" },
  { theme: "Romans 2", book: "Romans", passageRef: "Romans 2", testament: "new" },
  { theme: "Romans 3", book: "Romans", passageRef: "Romans 3", testament: "new" },
  { theme: "Romans 4-5", book: "Romans", passageRef: "Romans 4-5", testament: "new" },
  { theme: "Romans 6-7", book: "Romans", passageRef: "Romans 6-7", testament: "new" },
  { theme: "Romans 8", book: "Romans", passageRef: "Romans 8", testament: "new" },
  { theme: "Romans 9", book: "Romans", passageRef: "Romans 9", testament: "new" },
  { theme: "Romans 10", book: "Romans", passageRef: "Romans 10", testament: "new" },
  { theme: "Romans 11", book: "Romans", passageRef: "Romans 11", testament: "new" },
  { theme: "Romans 12-13", book: "Romans", passageRef: "Romans 12-13", testament: "new" },
  { theme: "Romans 14", book: "Romans", passageRef: "Romans 14", testament: "new" },
  { theme: "Romans 15", book: "Romans", passageRef: "Romans 15", testament: "new" },
  { theme: "Romans 16", book: "Romans", passageRef: "Romans 16", testament: "new" },
  { theme: "1 Corinthians 1-2", book: "1 Corinthians", passageRef: "1 Corinthians 1-2", testament: "new" },
  { theme: "1 Corinthians 3-4", book: "1 Corinthians", passageRef: "1 Corinthians 3-4", testament: "new" },
  { theme: "1 Corinthians 5-6", book: "1 Corinthians", passageRef: "1 Corinthians 5-6", testament: "new" },
  { theme: "1 Corinthians 7", book: "1 Corinthians", passageRef: "1 Corinthians 7", testament: "new" },
  { theme: "1 Corinthians 8-9", book: "1 Corinthians", passageRef: "1 Corinthians 8-9", testament: "new" },
  { theme: "1 Corinthians 10", book: "1 Corinthians", passageRef: "1 Corinthians 10", testament: "new" },
  { theme: "1 Corinthians 11", book: "1 Corinthians", passageRef: "1 Corinthians 11", testament: "new" },
  { theme: "1 Corinthians 12-13", book: "1 Corinthians", passageRef: "1 Corinthians 12-13", testament: "new" },
  { theme: "1 Corinthians 14", book: "1 Corinthians", passageRef: "1 Corinthians 14", testament: "new" },
  { theme: "1 Corinthians 15", book: "1 Corinthians", passageRef: "1 Corinthians 15", testament: "new" },
  { theme: "1 Corinthians 16", book: "1 Corinthians", passageRef: "1 Corinthians 16", testament: "new" },
  { theme: "2 Corinthians 1-2", book: "2 Corinthians", passageRef: "2 Corinthians 1-2", testament: "new" },
  { theme: "2 Corinthians 3-4", book: "2 Corinthians", passageRef: "2 Corinthians 3-4", testament: "new" },
  { theme: "2 Corinthians 5-6", book: "2 Corinthians", passageRef: "2 Corinthians 5-6", testament: "new" },
  { theme: "2 Corinthians 7-8", book: "2 Corinthians", passageRef: "2 Corinthians 7-8", testament: "new" },
  { theme: "2 Corinthians 9-10", book: "2 Corinthians", passageRef: "2 Corinthians 9-10", testament: "new" },
  { theme: "2 Corinthians 11", book: "2 Corinthians", passageRef: "2 Corinthians 11", testament: "new" },
  { theme: "2 Corinthians 12-13", book: "2 Corinthians", passageRef: "2 Corinthians 12-13", testament: "new" },
  { theme: "Galatians 1-2", book: "Galatians", passageRef: "Galatians 1-2", testament: "new" },
  { theme: "Galatians 3", book: "Galatians", passageRef: "Galatians 3", testament: "new" },
  { theme: "Galatians 4", book: "Galatians", passageRef: "Galatians 4", testament: "new" },
  { theme: "Galatians 5-6", book: "Galatians", passageRef: "Galatians 5-6", testament: "new" },
  { theme: "Ephesians 1-2", book: "Ephesians", passageRef: "Ephesians 1-2", testament: "new" },
  { theme: "Ephesians 3", book: "Ephesians", passageRef: "Ephesians 3", testament: "new" },
  { theme: "Ephesians 4", book: "Ephesians", passageRef: "Ephesians 4", testament: "new" },
  { theme: "Ephesians 5", book: "Ephesians", passageRef: "Ephesians 5", testament: "new" },
  { theme: "Ephesians 6", book: "Ephesians", passageRef: "Ephesians 6", testament: "new" },
  { theme: "Philippians 1", book: "Philippians", passageRef: "Philippians 1", testament: "new" },
  { theme: "Philippians 2-3", book: "Philippians", passageRef: "Philippians 2-3", testament: "new" },
  { theme: "Philippians 4", book: "Philippians", passageRef: "Philippians 4", testament: "new" },
  { theme: "Colossians 1-2", book: "Colossians", passageRef: "Colossians 1-2", testament: "new" },
  { theme: "Colossians 3-4", book: "Colossians", passageRef: "Colossians 3-4", testament: "new" },
  { theme: "1 Thessalonians 1-3", book: "1 Thessalonians", passageRef: "1 Thessalonians 1-3", testament: "new" },
  { theme: "1 Thessalonians 4-5", book: "1 Thessalonians", passageRef: "1 Thessalonians 4-5", testament: "new" },
  { theme: "2 Thessalonians 1-3", book: "2 Thessalonians", passageRef: "2 Thessalonians 1-3", testament: "new" },
  { theme: "1 Timothy 1-3", book: "1 Timothy", passageRef: "1 Timothy 1-3", testament: "new" },
  { theme: "1 Timothy 4-5", book: "1 Timothy", passageRef: "1 Timothy 4-5", testament: "new" },
  { theme: "1 Timothy 6", book: "1 Timothy", passageRef: "1 Timothy 6", testament: "new" },
  { theme: "2 Timothy 1-2", book: "2 Timothy", passageRef: "2 Timothy 1-2", testament: "new" },
  { theme: "2 Timothy 3-4", book: "2 Timothy", passageRef: "2 Timothy 3-4", testament: "new" },
  { theme: "Titus 1-3", book: "Titus", passageRef: "Titus 1-3", testament: "new" },
  { theme: "Philemon 1", book: "Philemon", passageRef: "Philemon 1", testament: "new" },
  { theme: "Hebrews 1-3", book: "Hebrews", passageRef: "Hebrews 1-3", testament: "new" },
  { theme: "Hebrews 4-6", book: "Hebrews", passageRef: "Hebrews 4-6", testament: "new" },
  { theme: "Hebrews 7-8", book: "Hebrews", passageRef: "Hebrews 7-8", testament: "new" },
  { theme: "Hebrews 9", book: "Hebrews", passageRef: "Hebrews 9", testament: "new" },
  { theme: "Hebrews 10", book: "Hebrews", passageRef: "Hebrews 10", testament: "new" },
  { theme: "Hebrews 11", book: "Hebrews", passageRef: "Hebrews 11", testament: "new" },
  { theme: "Hebrews 12", book: "Hebrews", passageRef: "Hebrews 12", testament: "new" },
  { theme: "Hebrews 13", book: "Hebrews", passageRef: "Hebrews 13", testament: "new" },
  { theme: "James 1", book: "James", passageRef: "James 1", testament: "new" },
];

const CHUNK_8: CurriculumEntry[] = [
  { theme: "James 2-3", book: "James", passageRef: "James 2-3", testament: "new" },
  { theme: "James 4-5", book: "James", passageRef: "James 4-5", testament: "new" },
  { theme: "1 Peter 1-2", book: "1 Peter", passageRef: "1 Peter 1-2", testament: "new" },
  { theme: "1 Peter 3-4", book: "1 Peter", passageRef: "1 Peter 3-4", testament: "new" },
  { theme: "1 Peter 5", book: "1 Peter", passageRef: "1 Peter 5", testament: "new" },
  { theme: "2 Peter 1-2", book: "2 Peter", passageRef: "2 Peter 1-2", testament: "new" },
  { theme: "2 Peter 3", book: "2 Peter", passageRef: "2 Peter 3", testament: "new" },
  { theme: "1 John 1-2", book: "1 John", passageRef: "1 John 1-2", testament: "new" },
  { theme: "1 John 3-4", book: "1 John", passageRef: "1 John 3-4", testament: "new" },
  { theme: "1 John 5", book: "1 John", passageRef: "1 John 5", testament: "new" },
  { theme: "2 John 1", book: "2 John", passageRef: "2 John 1", testament: "new" },
  { theme: "3 John 1", book: "3 John", passageRef: "3 John 1", testament: "new" },
  { theme: "Jude 1", book: "Jude", passageRef: "Jude 1", testament: "new" },
  { theme: "Revelation 1-2", book: "Revelation", passageRef: "Revelation 1-2", testament: "new" },
  { theme: "Revelation 3-5", book: "Revelation", passageRef: "Revelation 3-5", testament: "new" },
  { theme: "Revelation 6-8", book: "Revelation", passageRef: "Revelation 6-8", testament: "new" },
  { theme: "Revelation 9-11", book: "Revelation", passageRef: "Revelation 9-11", testament: "new" },
  { theme: "Revelation 12-13", book: "Revelation", passageRef: "Revelation 12-13", testament: "new" },
  { theme: "Revelation 14-16", book: "Revelation", passageRef: "Revelation 14-16", testament: "new" },
  { theme: "Revelation 17-18", book: "Revelation", passageRef: "Revelation 17-18", testament: "new" },
  { theme: "Revelation 19-20", book: "Revelation", passageRef: "Revelation 19-20", testament: "new" },
  { theme: "Revelation 21-22", book: "Revelation", passageRef: "Revelation 21-22", testament: "new" },
];

export const STARTER_CURRICULUM: CurriculumEntry[] = [
  ...CHUNK_0,
  ...CHUNK_1,
  ...CHUNK_2,
  ...CHUNK_3,
  ...CHUNK_4,
  ...CHUNK_5,
  ...CHUNK_6,
  ...CHUNK_7,
  ...CHUNK_8,
];
